# Generated by Django 3.2.6 on 2023-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230726_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$KHwe5Ir2PJLkJi8uXfDhjS$/KWnqGE6QDe6qK4i/iWGpBuGehhxX7Cq02QgxZ2KcGs=', max_length=128),
        ),
    ]
